name: Reusable Lint Workflow

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version'
        required: true
        default: '1.22'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run Linter
        run: |
          echo "Running golangci-lint"
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
